version: '3.8'

services:
  angular-app:
    container_name: fep-ui-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npx ng serve --host 0.0.0.0 --port 4200
